---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo-dev/apps
    repoURL: https://github.com/javdet/argocd-lesson.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

